export const LOAD_PRODCUTS_START = "LOAD_PRODCUTS_START"
export const LOAD_PRODCUTS_SUCCESS = "LOAD_PRODCUTS_SUCCESS"
export const LOAD_PRODCUTS_ERROR = "LOAD_PRODCUTS_ERROR"

export const LOAD_PRODCUTS_COLOR_START = "LOAD_PRODCUTS_COLOR_START"
export const LOAD_PRODCUTS_COLOR_SUCCESS = "LOAD_PRODCUTS_COLOR_SUCCESS"
export const LOAD_PRODCUTS_COLOR_ERROR = "LOAD_PRODCUTS_COLOR_ERROR"

export const LOAD_PRODCUTS_MATERIALS_START = "LOAD_PRODCUTS_MATERIALS_START"
export const LOAD_PRODCUTS_MATERIALS_SUCCESS = "LOAD_PRODCUTS_MATERIALS_SUCCESS"
export const LOAD_PRODCUTS_MATERIALS_ERROR = "LOAD_PRODCUTS_MATERIALS_ERROR"

export const LOAD_FEATURED_PRODCUTS_START = "LOAD_FEATURED_PRODCUTS_START"
export const LOAD_FEATURED_PRODCUTS_SUCCESS = "LOAD_FEATURED_PRODCUTS_SUCCESS"
export const LOAD_FEATURED_PRODCUTS_ERROR = "LOAD_FEATURED_PRODCUTS_ERROR"

export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

 export const REMOVE_FROM_CART_START = "REMOVE_FROM_CART_START";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_ERROR = "REMOVE_FROM_CART_ERROR";
